name: Publish Website

on:
  push:
    branches:
      - dev


jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3
    
    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: 35.212.192.186
        remote-user: trm
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: /home/trm/web/tanisharosemedia.com/public_html/wp-content/themes/trm_portfolio/